# 1. Pengambilan data ulasan di google play

In [1]:
from google_play_scraper import Sort, reviews_all
import pandas as pd
import numpy as np

In [2]:
scrapreview = reviews_all(
    'com.roblox.client',  # ID aplikasi
    lang='id',                 # defaults to 'id'
    country='id',              # defaults to 'id'
    sort=Sort.NEWEST,   # defaults to Sort.MOST_RELEVANT
    count=50,
    filter_score_with=None        # defaults to None (means all score)
)

In [4]:
data_roblox = pd.DataFrame(scrapreview)
data_roblox.head()

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion
0,ec7ced28-953f-4923-b2e6-27b5186aa431,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,seru banget,5,0,2.702.632,2025-12-22 14:50:57,None,None,2.702.632
1,a38ef8f6-dfe4-4687-a1e3-89e03fc1bad2,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,saat melapor pemain yang berkata kasar dan mem...,1,0,2.702.632,2025-12-22 14:49:57,None,None,2.702.632
2,e5dc2d3a-1a81-41a4-bcc2-6056db03a92c,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,sayang sekali item it boy doll 3D di hapus ken...,1,0,2.702.622,2025-12-22 14:48:26,None,None,2.702.622
3,8e043539-0888-4705-8613-a8fe80c10b0a,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,gamenya bagus tapi kalo untuk soal ngebug atau...,5,0,2.702.622,2025-12-22 14:45:40,None,None,2.702.622
4,0909534f-14a5-4c69-a8d6-c2b62b6c9ab7,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,"masa Roblox ku setiap bulan harus update,??",1,0,2.692.843,2025-12-22 14:45:28,None,None,2.692.843

In [5]:
len(data_roblox.index)

157500

In [6]:
review_data_roblox = data_roblox[['userName', 'score', 'at', 'content']]

In [8]:
review_data_roblox.to_csv("data_review_roblox.csv", index = False)
print ('data berhasil di simpan')

data berhasil di simpan

# 2. Pengambilan data komentar di twitter

In [22]:
X_auth_token = 'aec668168407f2623f886dca12712f380baf8830'

In [23]:
!pip install pandas
!curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash -
!sudo apt-get install -y nodejs

Requirement already satisfied: pandas in c:\users\asus\anaconda3\lib\site-packages (2.1.4)
Requirement already satisfied: numpy<2,>=1.23.2 in c:\users\asus\anaconda3\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\asus\anaconda3\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\asus\anaconda3\lib\site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\users\asus\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\asus\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

Sudo is disabled on this machine. To enable it, go to the ]8;;ms-settings:developers\Developer Settings page]8;;\ in the Settings app
Sudo is disabled on this machine. To enable it, go to the ]8;;ms-settings:developers\Developer Settings page]8;;\ in the Settings app

In [25]:
# crawl data
filename = 'Ibu.csv'
X_thread_url = 'https://x.com/tempodotco/status/2003110781731373263?s=20'
limit = 20

!npx --yes tweet-harvest@latest -o {filename} -l {limit} --token {X_auth_token} --thread {X_thread_url}

Tweet Harvest [v2.7.1]

Research by Helmi Satria
Use it for Educational Purposes only!

This script uses Chromium Browser to crawl data from Twitter with your Twitter auth token.
Please enter your Twitter auth token when prompted.

Note: Keep your access token secret! Don't share it with anyone else.
Note: This script only runs on your local device.


Opening twitter search page...


-- Scrolling... (1) (2)
-- Scrolling... (1)

Your tweets saved to: C:\Users\ASUS\Penambangan data\tweets-data\Ibu.csv
Total tweets saved: 36
Got 36 tweets, done scrolling...

[v2.7.1] No more tweets found, please check your search criteria and csv file result

In [26]:
import pandas as pd

file_path = f'tweets-data/{filename}'

data_komentar = pd.read_csv(file_path, delimiter=';')

display(data_komentar)

                                                   conversation_id_str,"created_at","favorite_count","full_text","id_str","image_url","in_reply_to_screen_name","lang","location","quote_count","reply_count","retweet_count","tweet_url","user_id_str","username"
2003110781731373263,"2025-12-22T20:06:13.000Z",...   korup memerintah kelamaan 🤔","200319539290587...
2003110781731373263,"2025-12-23T00:35:08.000Z",...                                                NaN
2003110781731373263,"2025-12-23T04:40:47.000Z",...                                                NaN
2003110781731373263,"2025-12-22T22:27:22.000Z",...                                                NaN
Hari ayah sudah                                                                                   NaN
Hari kakek nenek belum                                                                            NaN
Usul adain hari paman ke wapres @gibran_tweet",...                                                NaN
2003110781731373263,"2025-12-23T02:56:25.000Z",...                                                NaN
2003110781731373263,"2025-12-22T21:36:55.000Z",...                                                NaN
2003110781731373263,"2025-12-23T01:14:45.000Z",...                                                NaN
2003110781731373263,"2025-12-23T01:19:16.000Z",...                                                NaN
2003110781731373263,"2025-12-23T03:00:53.000Z",...                                                NaN
2003110781731373263,"2025-12-23T02:57:56.000Z",...                                                NaN
2003110781731373263,"2025-12-23T00:16:18.000Z",...                                                NaN
2003110781731373263,"2025-12-22T22:28:57.000Z",...                                                NaN
2003110781731373263,"2025-12-23T02:17:12.000Z",...                                                NaN
Jd 22 Des = hari perempuan Indonesia.","2003288...                                                NaN
2003110781731373263,"2025-12-23T06:48:26.000Z",...                                                NaN
🙃","2003357008351879595","","tempodotco","in","...                                                NaN
2003110781731373263,"2025-12-23T03:23:40.000Z",...                                                NaN
2003110781731373263,"2025-12-23T01:17:28.000Z",...                                                NaN
2003110781731373263,"2025-12-23T02:24:18.000Z",...                                                NaN
2003110781731373263,"2025-12-22T23:47:54.000Z",...                                                NaN
2003110781731373263,"2025-12-23T02:06:56.000Z",...                                                NaN
2003110781731373263,"2025-12-22T23:30:40.000Z",...                                                NaN
2003110781731373263,"2025-12-23T02:12:19.000Z",...                                                NaN
2003110781731373263,"2025-12-23T01:24:30.000Z",...                                                NaN
2003110781731373263,"2025-12-23T03:14:07.000Z",...                                                NaN
2003110781731373263,"2025-12-22T18:02:13.000Z",...                                                NaN
2003110781731373263,"2025-12-22T22:45:41.000Z",...                                                NaN
2003110781731373263,"2025-12-23T06:56:53.000Z",...                                                NaN
2003110781731373263,"2025-12-23T02:52:43.000Z",...                                                NaN
2003110781731373263,"2025-12-22T22:22:21.000Z",...                                                NaN
2003110781731373263,"2025-12-22T21:54:09.000Z",...                                                NaN
2003110781731373263,"2025-12-22T20:31:56.000Z",...                                                NaN
2003110781731373263,"2025-12-23T03:19:02.000Z",...                                                NaN
2003110781731373263,"2025-12-22T23:33:43.000Z",...                                                NaN
2003110781731373263,"2025-12-23T01:37:08.000Z",...                                                NaN
2003110781731373263,"2025-12-22T23:48:12.000Z",...                                                NaN
2003110781731373263,"2025-12-22T21:23:17.000Z",...                                                NaN
2003110781731373263,"2025-12-22T22:30:09.000Z",...                                                NaN

In [28]:
# cek jumlah data yang di dapatkan

num_tweets = len(data_komentar)
print(f'Jumlah tweets dalam dataframe adalah {num_tweets}.')

Jumlah tweets dalam dataframe adalah 41.

# 3.  referensi dan percobaan Crawling Instagram/tiktok dengan Instalooter/web scrap tiktok. 1 psotingan

In [1]:
pip install instaloader

Collecting instaloader
  Downloading instaloader-4.15-py3-none-any.whl.metadata (6.8 kB)
Requirement already satisfied: requests>=2.25 in c:\users\asus\anaconda3\lib\site-packages (from instaloader) (2.32.5)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\asus\anaconda3\lib\site-packages (from requests>=2.25->instaloader) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\asus\anaconda3\lib\site-packages (from requests>=2.25->instaloader) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\asus\anaconda3\lib\site-packages (from requests>=2.25->instaloader) (2.6.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\asus\anaconda3\lib\site-packages (from requests>=2.25->instaloader) (2025.10.5)
Downloading instaloader-4.15-py3-none-any.whl (68 kB)
   ---------------------------------------- 0.0/68.3 kB ? eta -:--:--
   ----- ---------------------------------- 10.2/68.3 kB ? eta -:--:--
   ----------------------- ---------------- 41.0/68.3 kB 495.5 kB/s eta 0:00:01
   ---------------------------------------- 68.3/68.3 kB 532.8 kB/s eta 0:00:00
Installing collected packages: instaloader
Successfully installed instaloader-4.15
Note: you may need to restart the kernel to use updated packages.

In [8]:
import instaloader
import pandas as pd

L = instaloader.Instaloader()

# login dulu
L.login("mpx25_5", "NW-2-p4C68PN2a7")

In [10]:
post_url = "https://www.instagram.com/p/DQJq_Lmkvg2/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA=="

shortcode = post_url.split("/p/")[1].split("/")[0]
post = instaloader.Post.from_shortcode(L.context, shortcode)

data = [{
    "username": post.owner_username,
    "caption": post.caption,
    "jumlah_like": post.likes,
    "jumlah_komentar": post.comments,
    "tanggal_post": post.date_utc
}]

df = pd.DataFrame(data)
df

,username,caption,jumlah_like,jumlah_komentar,tanggal_post
0,katarinabluu,눈빛에 어떤 역할이 있다면 진심을 느닷없이 말하기 좋다는 것,3457677,24669,2025-10-23 12:05:48

In [11]:
df.to_csv("instagram_1_postingan.csv", index=False)